"""empty message

Revision ID: 5d0e48e45e8a
Revises: 7ae5c1609937
Create Date: 2024-07-11 20:47:45.424248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0e48e45e8a'
down_revision = '7ae5c1609937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JobApplications', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('JobSearchCriteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JobSearchCriteria', schema=None) as batch_op:
        batch_op.drop_column('job_type')

    with op.batch_alter_table('JobApplications', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
