"""initial migration

Revision ID: b299da454f03
Revises: 
Create Date: 2024-07-12 01:50:46.940178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b299da454f03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JobApplications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=False))

    with op.batch_alter_table('JobSearchCriteria', schema=None) as batch_op:
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JobSearchCriteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('JobApplications', schema=None) as batch_op:
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
